plugins {
    id 'com.enonic.xp.app'
    id 'com.enonic.defaults' version '2.1.6'
    id 'maven-publish'
}

dependencies {
    implementation xplibs.api.core
    implementation xplibs.api.portal
    include xplibs.content
    include xplibs.portal
    include xplibs.export
    include xplibs.project
    include xplibs.cluster
    include libs.lib.thymeleaf
    webjar "org.webjars:bootstrap:5.3.8"
    webjar "org.webjars:jquery:4.0.0"
    webjar "org.webjars:html5shiv:3.7.3-1"
    webjar "org.webjars:respond:1.4.2-1"
    webjar "org.webjars:font-awesome:7.2.0"
}

repositories {
    mavenCentral()
    xp.enonicRepo("dev")
}
